meta_title: "HedgeNews: 1 actualité a plusieurs sources"
meta_description: "Retrouvez une variété d'articles provenant de diverses sources journalistiques"
meta_image: "hedgenews_meta_image.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@guicabanel" # indispensable pour les Twitter Cards
