meta_title: "HedgeNews - L'actualité a plusieurs sources"
meta_description: "HedgeNews vous propose une diversité des sources, pour vous aider à vous forger une opinion éclairée."
meta_image: "hedgenews_meta_image.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@guicabanel" # indispensable pour les Twitter Cards
